In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("flights.csv")

C:\Users\Dell\AppData\Local\Temp\ipykernel_404\2694568856.py:1: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("flights.csv")

In [3]:
df.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,408.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,741.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,811.0,5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,756.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,259.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.shape

(4531451, 31)

In [5]:
df.columns

Index(['YEAR', 'MONTH', 'DAY', 'DAY_OF_WEEK', 'AIRLINE', 'FLIGHT_NUMBER',
       'TAIL_NUMBER', 'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT',
       'SCHEDULED_DEPARTURE', 'DEPARTURE_TIME', 'DEPARTURE_DELAY', 'TAXI_OUT',
       'WHEELS_OFF', 'SCHEDULED_TIME', 'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE',
       'WHEELS_ON', 'TAXI_IN', 'SCHEDULED_ARRIVAL', 'ARRIVAL_TIME',
       'ARRIVAL_DELAY', 'DIVERTED', 'CANCELLED', 'CANCELLATION_REASON',
       'AIR_SYSTEM_DELAY', 'SECURITY_DELAY', 'AIRLINE_DELAY',
       'LATE_AIRCRAFT_DELAY', 'WEATHER_DELAY'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4531451 entries, 0 to 4531450
Data columns (total 31 columns):
 #   Column               Dtype
---  ------               -----
 0   YEAR                 int64
 1   MONTH                int64
 2   DAY                  int64
 3   DAY_OF_WEEK          int64
 4   AIRLINE              object
 5   FLIGHT_NUMBER        int64
 6   TAIL_NUMBER          object
 7   ORIGIN_AIRPORT       object
 8   DESTINATION_AIRPORT  object
 9   SCHEDULED_DEPARTURE  int64
 10  DEPARTURE_TIME       float64
 11  DEPARTURE_DELAY      float64
 12  TAXI_OUT             float64
 13  WHEELS_OFF           float64
 14  SCHEDULED_TIME       float64
 15  ELAPSED_TIME         float64
 16  AIR_TIME             float64
 17  DISTANCE             int64
 18  WHEELS_ON            float64
 19  TAXI_IN              float64
 20  SCHEDULED_ARRIVAL    int64
 21  ARRIVAL_TIME         float64
 22  ARRIVAL_DELAY        float64
 23  DIVERTED             int64
 24  CANCELLED            int64
 25  CANCELLATION_REASON  object
 26  AIR_SYSTEM_DELAY     float64
 27  SECURITY_DELAY       float64
 28  AIRLINE_DELAY        float64
 29  LATE_AIRCRAFT_DELAY  float64
 30  WEATHER_DELAY        float64
dtypes: float64(16), int64(10), object(5)
memory usage: 1.0+ GB

In [7]:
df.isnull().sum()

YEAR                         0
MONTH                        0
DAY                          0
DAY_OF_WEEK                  0
AIRLINE                      0
FLIGHT_NUMBER                0
TAIL_NUMBER              12822
ORIGIN_AIRPORT               0
DESTINATION_AIRPORT          0
SCHEDULED_DEPARTURE          0
DEPARTURE_TIME           72295
DEPARTURE_DELAY          72295
TAXI_OUT                 74653
WHEELS_OFF               74653
SCHEDULED_TIME               6
ELAPSED_TIME             87410
AIR_TIME                 87410
DISTANCE                     0
WHEELS_ON                77228
TAXI_IN                  77228
SCHEDULED_ARRIVAL            0
ARRIVAL_TIME             77228
ARRIVAL_DELAY            87410
DIVERTED                     0
CANCELLED                    0
CANCELLATION_REASON    4456153
AIR_SYSTEM_DELAY       3675215
SECURITY_DELAY         3675215
AIRLINE_DELAY          3675215
LATE_AIRCRAFT_DELAY    3675215
WEATHER_DELAY          3675215
dtype: int64

In [9]:
delay_cols = [
    'AIR_SYSTEM_DELAY',
    'SECURITY_DELAY',
    'AIRLINE_DELAY',
    'LATE_AIRCRAFT_DELAY',
    'WEATHER_DELAY'
]

df[delay_cols] = df[delay_cols].fillna(0)

In [11]:
df['CANCELLATION_REASON'] = df['CANCELLATION_REASON'].fillna('Not Cancelled')
df["CANCELLATION_REASON"] = df["CANCELLATION_REASON"].replace({
    "A": "Carrier",
    "B": "Weather",
    "C": "NAS",
    "D": "Security"
})

In [15]:
df.loc[df['CANCELLED'] == 1, ['DEPARTURE_DELAY','ARRIVAL_DELAY']] = 0
time_columns = [
    'DEPARTURE_TIME', 'ARRIVAL_TIME',
    'TAXI_OUT', 'TAXI_IN',
    'WHEELS_OFF', 'WHEELS_ON',
    'AIR_TIME', 'ELAPSED_TIME'
]

df.loc[df['CANCELLED'] == 1, time_columns] = 0
df['TAIL_NUMBER'] = df['TAIL_NUMBER'].fillna('Unknown')
df['SCHEDULED_TIME'] = df['SCHEDULED_TIME'].fillna(df['SCHEDULED_TIME'].median())
diverted_cols = [
    'ELAPSED_TIME', 'AIR_TIME', 'ARRIVAL_DELAY',
    'WHEELS_ON', 'TAXI_IN', 'ARRIVAL_TIME'
]

df.loc[df['DIVERTED'] == 1, diverted_cols] = 0

# Project Workflow

1. Data Loading and Initial Exploration
2. Data Cleaning and Null Handling
3. Feature Engineering
4. Memory Optimization
5. KPI Calculation
6. Saving Cleaned Dataset for Future Analysis

In [16]:
df.isnull().sum()

YEAR                   0
MONTH                  0
DAY                    0
DAY_OF_WEEK            0
AIRLINE                0
FLIGHT_NUMBER          0
TAIL_NUMBER            0
ORIGIN_AIRPORT         0
DESTINATION_AIRPORT    0
SCHEDULED_DEPARTURE    0
DEPARTURE_TIME         0
DEPARTURE_DELAY        0
TAXI_OUT               0
WHEELS_OFF             0
SCHEDULED_TIME         0
ELAPSED_TIME           0
AIR_TIME               0
DISTANCE               0
WHEELS_ON              0
TAXI_IN                0
SCHEDULED_ARRIVAL      0
ARRIVAL_TIME           0
ARRIVAL_DELAY          0
DIVERTED               0
CANCELLED              0
CANCELLATION_REASON    0
AIR_SYSTEM_DELAY       0
SECURITY_DELAY         0
AIRLINE_DELAY          0
LATE_AIRCRAFT_DELAY    0
WEATHER_DELAY          0
dtype: int64

In [17]:
df['MONTH_NAME'] = df['MONTH'].map({
    1: 'January', 2: 'February', 3: 'March', 4: 'April',
    5: 'May', 6: 'June', 7: 'July', 8: 'August',
    9: 'September', 10: 'October', 11: 'November', 12: 'December'
})

In [18]:
df[['MONTH', 'MONTH_NAME']].head()

   MONTH MONTH_NAME
0      1    January
1      1    January
2      1    January
3      1    January
4      1    January

In [19]:
df['DAY_NAME'] = df['DAY_OF_WEEK'].map({
    1: 'Monday',
    2: 'Tuesday',
    3: 'Wednesday',
    4: 'Thursday',
    5: 'Friday',
    6: 'Saturday',
    7: 'Sunday'
})

In [20]:
df[['DAY_OF_WEEK', 'DAY_NAME']].head()

   DAY_OF_WEEK  DAY_NAME
0            4  Thursday
1            4  Thursday
2            4  Thursday
3            4  Thursday
4            4  Thursday

In [21]:
df['ROUTE'] = df['ORIGIN_AIRPORT'].astype(str) + ' → ' + df['DESTINATION_AIRPORT'].astype(str)

In [22]:
df[['ORIGIN_AIRPORT', 'DESTINATION_AIRPORT', 'ROUTE']].head()

  ORIGIN_AIRPORT DESTINATION_AIRPORT      ROUTE
0            ANC                 SEA  ANC → SEA
1            LAX                 PBI  LAX → PBI
2            SFO                 CLT  SFO → CLT
3            LAX                 MIA  LAX → MIA
4            SEA                 ANC  SEA → ANC

In [24]:
df['DEP_HOUR'] = df['SCHEDULED_DEPARTURE'] // 100

In [25]:
df.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY,MONTH_NAME,DAY_NAME,ROUTE,IS_DELAYED,DEP_HOUR
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,0.0,0.0,0.0,0.0,0.0,January,Thursday,ANC → SEA,0,0
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,0.0,0.0,0.0,0.0,0.0,January,Thursday,LAX → PBI,0,0
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,0.0,0.0,0.0,0.0,0.0,January,Thursday,SFO → CLT,0,0
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,0.0,0.0,0.0,0.0,0.0,January,Thursday,LAX → MIA,0,0
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,0.0,0.0,0.0,0.0,0.0,January,Thursday,SEA → ANC,0,0

In [26]:
categorical_cols = [
    'AIRLINE',
    'ORIGIN_AIRPORT',
    'DESTINATION_AIRPORT',
    'CANCELLATION_REASON',
    'DAY_NAME',
    'MONTH_NAME'
]

for col in categorical_cols:
    df[col] = df[col].astype('category')

# Key Performance Indicators (KPIs)

KPIs (Key Performance Indicators) are measurable metrics used to evaluate airline operational performance.

The following KPIs are calculated for this project:

1. Total Flights  
   Total number of flights in the dataset.

2. Cancellation Rate  
   Percentage of flights that were cancelled.

3. Average Arrival Delay  
   Average delay time (in minutes) for arriving flights.

4. Average Departure Delay  
   Average delay time (in minutes) for departing flights.

5. On-Time Performance Rate  
   Percentage of flights arriving within 15 minutes of scheduled arrival time.

6. Delay Cause Distribution  
   Total delay minutes categorized by:
   - Airline Delay
   - Weather Delay
   - Air System (NAS) Delay
   - Security Delay
   - Late Aircraft Delay

In [ ]:
df.to_csv("cleaned_flights_dataset_.csv", index=False)