In [1]:
import pandas as pd
import numpy as np

In [1]:
df = pd.read_csv(r"D:\college files\flights.csv",low_memory=False)

NameError: name 'pd' is not defined

In [13]:
df

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,408.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,741.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,811.0,5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,756.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,259.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5819074,2015,12,31,4,B6,688,N657JB,LAX,BOS,2359,...,753.0,-26.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5819075,2015,12,31,4,B6,745,N828JB,JFK,PSE,2359,...,430.0,-16.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5819076,2015,12,31,4,B6,1503,N913JB,JFK,SJU,2359,...,432.0,-8.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5819077,2015,12,31,4,B6,333,N527JB,MCO,SJU,2359,...,330.0,-10.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5819078,2015,12,31,4,B6,839,N534JB,JFK,BQN,2359,...,442.0,2.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
temp = df[df["CANCELLED"] == 1]
print(len(temp))

89884

In [3]:
df.isnull().sum()

YEAR                         0
MONTH                        0
DAY                          0
DAY_OF_WEEK                  0
AIRLINE                      0
FLIGHT_NUMBER                0
TAIL_NUMBER              14721
ORIGIN_AIRPORT               0
DESTINATION_AIRPORT          0
SCHEDULED_DEPARTURE          0
DEPARTURE_TIME           86153
DEPARTURE_DELAY          86153
TAXI_OUT                 89047
WHEELS_OFF               89047
SCHEDULED_TIME               6
ELAPSED_TIME            105071
AIR_TIME                105071
DISTANCE                     0
WHEELS_ON                92513
TAXI_IN                  92513
SCHEDULED_ARRIVAL            0
ARRIVAL_TIME             92513
ARRIVAL_DELAY           105071
DIVERTED                     0
CANCELLED                    0
CANCELLATION_REASON    5729195
AIR_SYSTEM_DELAY       4755640
SECURITY_DELAY         4755640
AIRLINE_DELAY          4755640
LATE_AIRCRAFT_DELAY    4755640
WEATHER_DELAY          4755640
dtype: int64

In [8]:
df["TAIL_NUMBER"]

0          N407AS
1          N3KUAA
2          N171US
3          N3HYAA
4          N527AS
            ...
5819074    N657JB
5819075    N828JB
5819076    N913JB
5819077    N527JB
5819078    N534JB
Name: TAIL_NUMBER, Length: 5819079, dtype: object

In [15]:
arr = df["TAIL_NUMBER"].unique()

In [19]:
print(len(arr))

4898

In [25]:
temp = df[df["AIRLINE"]=="AA"]
temp

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,741.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,756.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
8,2015,1,1,4,AA,1112,N3LAAA,SFO,DFW,30,...,532.0,-13.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
11,2015,1,1,4,AA,1674,N853AA,LAS,MIA,35,...,753.0,-10.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
21,2015,1,1,4,AA,371,N3GXAA,SEA,MIA,100,...,939.0,1.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5819031,2015,12,31,4,AA,1927,N837AW,LAX,IAD,2349,...,712.0,-26.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5819035,2015,12,31,4,AA,675,N207UW,HNL,PHX,2350,...,818.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5819049,2015,12,31,4,AA,1538,N866AA,LAX,MIA,2355,...,731.0,-17.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5819067,2015,12,31,4,AA,2342,N3DLAA,DEN,MIA,2359,...,525.0,-18.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5819068,2015,12,31,4,AA,219,N3LYAA,LAX,ORD,2359,...,544.0,-19.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
t_arr = temp["TAIL_NUMBER"].unique()

In [39]:
temp1 = df[(df["ORIGIN_AIRPORT"] == "MSO" ) & (df["DESTINATION_AIRPORT"] == "DEN")]

In [46]:
temp1.head(20)

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
297,2015,1,1,4,F9,865,NaN,MSO,DEN,600,...,NaN,NaN,0,1,A,NaN,NaN,NaN,NaN,NaN
2201,2015,1,1,4,OO,5534,N928SW,MSO,DEN,840,...,1101.0,16.0,0,0,NaN,16.0,0.0,0.0,0.0,0.0
5849,2015,1,1,4,OO,5578,N943SW,MSO,DEN,1244,...,1637.0,117.0,0,0,NaN,0.0,0.0,117.0,0.0,0.0
10083,2015,1,1,4,OO,5519,N479CA,MSO,DEN,1712,...,1921.0,11.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
17475,2015,1,2,5,OO,5534,N969SW,MSO,DEN,840,...,1302.0,137.0,0,0,NaN,0.0,0.0,137.0,0.0,0.0
21537,2015,1,2,5,OO,5535,N983SW,MSO,DEN,1244,...,1619.0,99.0,0,0,NaN,27.0,0.0,12.0,60.0,0.0
26060,2015,1,2,5,OO,5519,N905SW,MSO,DEN,1712,...,1920.0,10.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
31250,2015,1,3,6,F9,865,N910FR,MSO,DEN,600,...,753.0,-7.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
33950,2015,1,3,6,OO,5534,N941SW,MSO,DEN,840,...,1055.0,10.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
37732,2015,1,3,6,OO,5519,N702BR,MSO,DEN,1244,...,1534.0,54.0,0,0,NaN,19.0,0.0,4.0,31.0,0.0
46690,2015,1,4,7,F9,865,N918FR,MSO,DEN,600,...,803.0,3.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
49152,2015,1,4,7,OO,5534,N716SK,MSO,DEN,825,...,NaN,NaN,0,1,C,NaN,NaN,NaN,NaN,NaN
53418,2015,1,4,7,OO,6413,N679SA,MSO,DEN,1244,...,1611.0,91.0,0,0,NaN,44.0,0.0,7.0,40.0,0.0
57860,2015,1,4,7,OO,5519,N594SW,MSO,DEN,1712,...,1927.0,17.0,0,0,NaN,17.0,0.0,0.0,0.0,0.0
65985,2015,1,5,1,OO,5534,N929SW,MSO,DEN,840,...,NaN,NaN,0,1,B,NaN,NaN,NaN,NaN,NaN
70039,2015,1,5,1,OO,5535,N702BR,MSO,DEN,1244,...,1545.0,65.0,0,0,NaN,39.0,0.0,0.0,26.0,0.0
74574,2015,1,5,1,OO,5519,N693BR,MSO,DEN,1712,...,1938.0,28.0,0,0,NaN,0.0,0.0,0.0,28.0,0.0
79586,2015,1,6,2,F9,865,N905FR,MSO,DEN,600,...,735.0,-25.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
90253,2015,1,6,2,OO,5519,N764SK,MSO,DEN,1658,...,1902.0,2.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
105744,2015,1,7,3,OO,5519,N758SK,MSO,DEN,1703,...,1913.0,8.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df["CANCELLATION_REASON"] = df["CANCELLATION_REASON"].fillna("N")

In [20]:
df.isnull().sum()

YEAR                        0
MONTH                       0
DAY                         0
DAY_OF_WEEK                 0
AIRLINE                     0
FLIGHT_NUMBER               0
TAIL_NUMBER             14721
ORIGIN_AIRPORT              0
DESTINATION_AIRPORT         0
SCHEDULED_DEPARTURE         0
DEPARTURE_TIME          86153
DEPARTURE_DELAY         86153
TAXI_OUT                89047
WHEELS_OFF              89047
SCHEDULED_TIME              6
ELAPSED_TIME           105071
AIR_TIME               105071
DISTANCE                    0
WHEELS_ON               92513
TAXI_IN                 92513
SCHEDULED_ARRIVAL           0
ARRIVAL_TIME            92513
ARRIVAL_DELAY          105071
DIVERTED                    0
CANCELLED                   0
CANCELLATION_REASON         0
AIR_SYSTEM_DELAY            0
SECURITY_DELAY              0
AIRLINE_DELAY               0
LATE_AIRCRAFT_DELAY         0
WEATHER_DELAY               0
dtype: int64

In [5]:
df["CANCELLATION_REASON"] = "N"  # default

In [4]:
df["AIR_SYSTEM_DELAY"] = df["AIR_SYSTEM_DELAY"].fillna(0)
df["SECURITY_DELAY"] = df["SECURITY_DELAY"].fillna(0)
df["AIRLINE_DELAY"] = df["AIRLINE_DELAY"].fillna(0)
df["LATE_AIRCRAFT_DELAY"] = df["LATE_AIRCRAFT_DELAY"].fillna(0)
df["WEATHER_DELAY"] = df["WEATHER_DELAY"].fillna(0)

In [6]:
temp = df[df["TAXI_OUT"].isna()]

In [31]:
temp.isnull().sum()

YEAR                       0
MONTH                      0
DAY                        0
DAY_OF_WEEK                0
AIRLINE                    0
FLIGHT_NUMBER              0
TAIL_NUMBER            14721
ORIGIN_AIRPORT             0
DESTINATION_AIRPORT        0
SCHEDULED_DEPARTURE        0
DEPARTURE_TIME         86153
DEPARTURE_DELAY        86153
TAXI_OUT               89047
WHEELS_OFF             89047
SCHEDULED_TIME             0
ELAPSED_TIME           89047
AIR_TIME               89047
DISTANCE                   0
WHEELS_ON              89047
TAXI_IN                89047
SCHEDULED_ARRIVAL          0
ARRIVAL_TIME           89047
ARRIVAL_DELAY          89047
DIVERTED                   0
CANCELLED                  0
CANCELLATION_REASON        0
AIR_SYSTEM_DELAY           0
SECURITY_DELAY             0
AIRLINE_DELAY              0
LATE_AIRCRAFT_DELAY        0
WEATHER_DELAY              0
dtype: int64

In [33]:
temp.head(20)

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
32,2015,1,1,4,AS,136,N431AS,ANC,SEA,135,...,NaN,NaN,0,1,A,0.0,0.0,0.0,0.0,0.0
42,2015,1,1,4,AA,2459,N3BDAA,PHX,DFW,200,...,NaN,NaN,0,1,B,0.0,0.0,0.0,0.0,0.0
68,2015,1,1,4,OO,5254,N746SK,MAF,IAH,510,...,NaN,NaN,0,1,B,0.0,0.0,0.0,0.0,0.0
82,2015,1,1,4,MQ,2859,N660MQ,SGF,DFW,525,...,NaN,NaN,0,1,B,0.0,0.0,0.0,0.0,0.0
90,2015,1,1,4,OO,5460,N583SW,RDD,SFO,530,...,NaN,NaN,0,1,A,0.0,0.0,0.0,0.0,0.0
128,2015,1,1,4,MQ,2926,N932MQ,CHS,DFW,545,...,NaN,NaN,0,1,B,0.0,0.0,0.0,0.0,0.0
131,2015,1,1,4,OO,6457,N560SW,SMX,LAX,545,...,NaN,NaN,0,1,A,0.0,0.0,0.0,0.0,0.0
147,2015,1,1,4,MQ,3534,N925MQ,ABI,DFW,550,...,NaN,NaN,0,1,B,0.0,0.0,0.0,0.0,0.0
166,2015,1,1,4,MQ,3161,N5PBMQ,XNA,DFW,555,...,NaN,NaN,0,1,B,0.0,0.0,0.0,0.0,0.0
206,2015,1,1,4,AA,175,N3EWAA,DCA,DFW,600,...,NaN,NaN,0,1,B,0.0,0.0,0.0,0.0,0.0
210,2015,1,1,4,AA,1103,N3HCAA,LGA,DFW,600,...,NaN,NaN,0,1,B,0.0,0.0,0.0,0.0,0.0
213,2015,1,1,4,AA,1055,N573AA,MCO,DFW,600,...,NaN,NaN,0,1,B,0.0,0.0,0.0,0.0,0.0
214,2015,1,1,4,AA,1180,N3AYAA,SFO,DFW,600,...,NaN,NaN,0,1,B,0.0,0.0,0.0,0.0,0.0
265,2015,1,1,4,AA,1462,N547AA,ONT,DFW,600,...,NaN,NaN,0,1,B,0.0,0.0,0.0,0.0,0.0
297,2015,1,1,4,F9,865,NaN,MSO,DEN,600,...,NaN,NaN,0,1,A,0.0,0.0,0.0,0.0,0.0
298,2015,1,1,4,F9,1256,NaN,ORD,MIA,600,...,NaN,NaN,0,1,A,0.0,0.0,0.0,0.0,0.0
306,2015,1,1,4,MQ,2898,N514MQ,MAF,DFW,600,...,NaN,NaN,0,1,B,0.0,0.0,0.0,0.0,0.0
307,2015,1,1,4,MQ,2957,N504MQ,AMA,DFW,600,...,NaN,NaN,0,1,B,0.0,0.0,0.0,0.0,0.0
308,2015,1,1,4,MQ,2962,N609MQ,CLL,DFW,600,...,NaN,NaN,0,1,B,0.0,0.0,0.0,0.0,0.0
309,2015,1,1,4,MQ,3014,N908MQ,HOU,DFW,600,...,NaN,NaN,0,1,B,0.0,0.0,0.0,0.0,0.0

In [35]:
df["TAIL_NUMBER"] = df["TAIL_NUMBER"].fillna("Cancel")

In [7]:
df["DEPARTURE_TIME"] = df["DEPARTURE_TIME"].fillna(0)
df["DEPARTURE_DELAY"] = df["DEPARTURE_DELAY"].fillna(0)
df["TAXI_OUT"] = df["TAXI_OUT"].fillna(0)
df["WHEELS_OFF"] = df["WHEELS_OFF"].fillna(0)
df["ELAPSED_TIME"] = df["ELAPSED_TIME"].fillna(0)
df["AIR_TIME"] = df["AIR_TIME"].fillna(0)
df["WHEELS_ON"] = df["WHEELS_ON"].fillna(0)
df["ARRIVAL_TIME"] = df["ARRIVAL_TIME"].fillna(0)
df["ARRIVAL_DELAY"] = df["ARRIVAL_DELAY"].fillna(0)
df["TAXI_IN"] = df["TAXI_IN"].fillna(0)

YEAR                       0
MONTH                      0
DAY                        0
DAY_OF_WEEK                0
AIRLINE                    0
FLIGHT_NUMBER              0
TAIL_NUMBER            14721
ORIGIN_AIRPORT             0
DESTINATION_AIRPORT        0
SCHEDULED_DEPARTURE        0
DEPARTURE_TIME             0
DEPARTURE_DELAY            0
TAXI_OUT                   0
WHEELS_OFF                 0
SCHEDULED_TIME             6
ELAPSED_TIME               0
AIR_TIME                   0
DISTANCE                   0
WHEELS_ON                  0
TAXI_IN                    0
SCHEDULED_ARRIVAL          0
ARRIVAL_TIME               0
ARRIVAL_DELAY              0
DIVERTED                   0
CANCELLED                  0
CANCELLATION_REASON        0
AIR_SYSTEM_DELAY           0
SECURITY_DELAY             0
AIRLINE_DELAY              0
LATE_AIRCRAFT_DELAY        0
WEATHER_DELAY              0
dtype: int64

In [10]:
 
 
columns_to_remove = [
    'FLIGHT_NUMBER',
    'TAIL_NUMBER',
    'SCHEDULED_DEPARTURE',
    'DEPARTURE_TIME',
    'TAXI_OUT',
    'WHEELS_OFF',
    'SCHEDULED_TIME',
    'ELAPSED_TIME',
    'AIR_TIME',
    'WHEELS_ON',
    'TAXI_IN',
    'SCHEDULED_ARRIVAL',
    'ARRIVAL_TIME'
]

 
df = df.drop(columns=columns_to_remove)

 
print(df.columns)

Index(['YEAR', 'MONTH', 'DAY', 'DAY_OF_WEEK', 'AIRLINE', 'ORIGIN_AIRPORT',
       'DESTINATION_AIRPORT', 'DEPARTURE_DELAY', 'DISTANCE', 'ARRIVAL_DELAY',
       'DIVERTED', 'CANCELLED', 'CANCELLATION_REASON', 'AIR_SYSTEM_DELAY',
       'SECURITY_DELAY', 'AIRLINE_DELAY', 'LATE_AIRCRAFT_DELAY',
       'WEATHER_DELAY'],
      dtype='object')

In [11]:
df.to_csv("cleaned_flight_data.csv", index=False)