In [1]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [3]:
import pandas as pd
import numpy as np

In [4]:
# Load dataset (low_memory=False avoids dtype warnings)
df = pd.read_csv('/content/drive/MyDrive/flights.csv', low_memory=False)

In [5]:
# Basic info Check number of rows and columns
print(df.shape)

(5819079, 31)

In [6]:
# first 5 rows
df.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,408.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,741.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,811.0,5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,756.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,259.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# Check column names, data types, non-null counts
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5819079 entries, 0 to 5819078
Data columns (total 31 columns):
 #   Column               Dtype
---  ------               -----
 0   YEAR                 int64
 1   MONTH                int64
 2   DAY                  int64
 3   DAY_OF_WEEK          int64
 4   AIRLINE              object
 5   FLIGHT_NUMBER        int64
 6   TAIL_NUMBER          object
 7   ORIGIN_AIRPORT       object
 8   DESTINATION_AIRPORT  object
 9   SCHEDULED_DEPARTURE  int64
 10  DEPARTURE_TIME       float64
 11  DEPARTURE_DELAY      float64
 12  TAXI_OUT             float64
 13  WHEELS_OFF           float64
 14  SCHEDULED_TIME       float64
 15  ELAPSED_TIME         float64
 16  AIR_TIME             float64
 17  DISTANCE             int64
 18  WHEELS_ON            float64
 19  TAXI_IN              float64
 20  SCHEDULED_ARRIVAL    int64
 21  ARRIVAL_TIME         float64
 22  ARRIVAL_DELAY        float64
 23  DIVERTED             int64
 24  CANCELLED            int64
 25  CANCELLATION_REASON  object
 26  AIR_SYSTEM_DELAY     float64
 27  SECURITY_DELAY       float64
 28  AIRLINE_DELAY        float64
 29  LATE_AIRCRAFT_DELAY  float64
 30  WEATHER_DELAY        float64
dtypes: float64(16), int64(10), object(5)
memory usage: 1.3+ GB
None

In [8]:
# Check missing values in each column
print(df.isnull().sum())

YEAR                         0
MONTH                        0
DAY                          0
DAY_OF_WEEK                  0
AIRLINE                      0
FLIGHT_NUMBER                0
TAIL_NUMBER              14721
ORIGIN_AIRPORT               0
DESTINATION_AIRPORT          0
SCHEDULED_DEPARTURE          0
DEPARTURE_TIME           86153
DEPARTURE_DELAY          86153
TAXI_OUT                 89047
WHEELS_OFF               89047
SCHEDULED_TIME               6
ELAPSED_TIME            105071
AIR_TIME                105071
DISTANCE                     0
WHEELS_ON                92513
TAXI_IN                  92513
SCHEDULED_ARRIVAL            0
ARRIVAL_TIME             92513
ARRIVAL_DELAY           105071
DIVERTED                     0
CANCELLED                    0
CANCELLATION_REASON    5729195
AIR_SYSTEM_DELAY       4755640
SECURITY_DELAY         4755640
AIRLINE_DELAY          4755640
LATE_AIRCRAFT_DELAY    4755640
WEATHER_DELAY          4755640
dtype: int64

In [9]:
 # numeric columns  Useful to detect: Outliers,  Negative delays, Abnormal values
 df.describe()

,YEAR,MONTH,DAY,DAY_OF_WEEK,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,WHEELS_OFF,...,SCHEDULED_ARRIVAL,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
count,5819079.0,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.732926e+06,5.732926e+06,5.730032e+06,5.730032e+06,...,5.819079e+06,5.726566e+06,5.714008e+06,5.819079e+06,5.819079e+06,1.063439e+06,1.063439e+06,1.063439e+06,1.063439e+06,1.063439e+06
mean,2015.0,6.524085e+00,1.570459e+01,3.926941e+00,2.173093e+03,1.329602e+03,1.335204e+03,9.370158e+00,1.607166e+01,1.357171e+03,...,1.493808e+03,1.476491e+03,4.407057e+00,2.609863e-03,1.544643e-02,1.348057e+01,7.615387e-02,1.896955e+01,2.347284e+01,2.915290e+00
std,0.0,3.405137e+00,8.783425e+00,1.988845e+00,1.757064e+03,4.837518e+02,4.964233e+02,3.708094e+01,8.895574e+00,4.980094e+02,...,5.071647e+02,5.263197e+02,3.927130e+01,5.102012e-02,1.233201e-01,2.800368e+01,2.143460e+00,4.816164e+01,4.319702e+01,2.043334e+01
min,2015.0,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,-8.200000e+01,1.000000e+00,1.000000e+00,...,1.000000e+00,1.000000e+00,-8.700000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2015.0,4.000000e+00,8.000000e+00,2.000000e+00,7.300000e+02,9.170000e+02,9.210000e+02,-5.000000e+00,1.100000e+01,9.350000e+02,...,1.110000e+03,1.059000e+03,-1.300000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2015.0,7.000000e+00,1.600000e+01,4.000000e+00,1.690000e+03,1.325000e+03,1.330000e+03,-2.000000e+00,1.400000e+01,1.343000e+03,...,1.520000e+03,1.512000e+03,-5.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,2.000000e+00,3.000000e+00,0.000000e+00
75%,2015.0,9.000000e+00,2.300000e+01,6.000000e+00,3.230000e+03,1.730000e+03,1.740000e+03,7.000000e+00,1.900000e+01,1.754000e+03,...,1.918000e+03,1.917000e+03,8.000000e+00,0.000000e+00,0.000000e+00,1.800000e+01,0.000000e+00,1.900000e+01,2.900000e+01,0.000000e+00
max,2015.0,1.200000e+01,3.100000e+01,7.000000e+00,9.855000e+03,2.359000e+03,2.400000e+03,1.988000e+03,2.250000e+02,2.400000e+03,...,2.400000e+03,2.400000e+03,1.971000e+03,1.000000e+00,1.000000e+00,1.134000e+03,5.730000e+02,1.971000e+03,1.331000e+03,1.211000e+03

In [10]:
# Count number of unique values in each column
df.nunique().sort_values()

YEAR                      1
DIVERTED                  2
CANCELLED                 2
CANCELLATION_REASON       4
DAY_OF_WEEK               7
MONTH                    12
AIRLINE                  14
DAY                      31
SECURITY_DELAY          154
TAXI_OUT                184
TAXI_IN                 185
SCHEDULED_TIME          550
AIR_SYSTEM_DELAY        570
ORIGIN_AIRPORT          628
DESTINATION_AIRPORT     629
WEATHER_DELAY           632
AIR_TIME                675
LATE_AIRCRAFT_DELAY     695
ELAPSED_TIME            712
AIRLINE_DELAY          1067
DEPARTURE_DELAY        1217
ARRIVAL_DELAY          1240
SCHEDULED_DEPARTURE    1321
DISTANCE               1363
SCHEDULED_ARRIVAL      1435
WHEELS_ON              1440
WHEELS_OFF             1440
DEPARTURE_TIME         1440
ARRIVAL_TIME           1440
TAIL_NUMBER            4897
FLIGHT_NUMBER          6952
dtype: int64

In [11]:
# Store dtypes before optimization
dtypes_before = df.dtypes

In [12]:
memory_before = df.memory_usage(deep=True).sum() / 1024**2
print("Memory Before:", memory_before, "MB")

print(df.dtypes.value_counts())

Memory Before: 2500.3381423950195 MB
float64    16
int64      10
object      5
Name: count, dtype: int64

In [14]:
# -------- Memory Optimization --------
# Convert object columns with low unique values to 'category'
#This reduces memory usage significantly
for col in df.select_dtypes(include="object").columns:
    if df[col].nunique() < 0.5 * len(df):
        df[col] = df[col].astype("category")

In [15]:
# Downcast int64 to smaller integer types (int32/int16)
#This reduces memory usage without losing data
for col in df.select_dtypes(include="int64").columns:
    df[col] = pd.to_numeric(df[col], downcast="integer")

In [16]:
# Downcast float64 to float32
#Saves memory, especially useful for large datasets
for col in df.select_dtypes(include="float64").columns:
    df[col] = pd.to_numeric(df[col], downcast="float")

In [17]:
memory_after = df.memory_usage(deep=True).sum() / 1024**2

print("Memory After:", memory_after, "MB")
print("Memory Reduced:", memory_before - memory_after, "MB")

print(df.dtypes.value_counts())

Memory After: 483.28665828704834 MB
Memory Reduced: 2017.0514841079712 MB
float32     16
int16        5
int8         5
category     1
category     1
category     1
category     1
category     1
Name: count, dtype: int64

In [18]:
#stores datatypes after optimization
dtypes_after = df.dtypes

In [19]:
# Combine into one dataframe for comparison
comparison = pd.DataFrame({
    "Before": dtypes_before,
    "After": dtypes_after
})

print(comparison[comparison["Before"] != comparison["After"]])

                      Before     After
YEAR                   int64     int16
MONTH                  int64      int8
DAY                    int64      int8
DAY_OF_WEEK            int64      int8
AIRLINE               object  category
FLIGHT_NUMBER          int64     int16
TAIL_NUMBER           object  category
ORIGIN_AIRPORT        object  category
DESTINATION_AIRPORT   object  category
SCHEDULED_DEPARTURE    int64     int16
DEPARTURE_TIME       float64   float32
DEPARTURE_DELAY      float64   float32
TAXI_OUT             float64   float32
WHEELS_OFF           float64   float32
SCHEDULED_TIME       float64   float32
ELAPSED_TIME         float64   float32
AIR_TIME             float64   float32
DISTANCE               int64     int16
WHEELS_ON            float64   float32
TAXI_IN              float64   float32
SCHEDULED_ARRIVAL      int64     int16
ARRIVAL_TIME         float64   float32
ARRIVAL_DELAY        float64   float32
DIVERTED               int64      int8
CANCELLED              int64      int8
CANCELLATION_REASON   object  category
AIR_SYSTEM_DELAY     float64   float32
SECURITY_DELAY       float64   float32
AIRLINE_DELAY        float64   float32
LATE_AIRCRAFT_DELAY  float64   float32
WEATHER_DELAY        float64   float32

In [13]:
# -------- HANDLING MISSING VALUES --------
print("Missing Values BEFORE:")
print(df[["ARRIVAL_DELAY", "DEPARTURE_DELAY", "CANCELLED"]].isnull().sum())

Missing Values BEFORE:
ARRIVAL_DELAY      105071
DEPARTURE_DELAY     86153
CANCELLED               0
dtype: int64

In [20]:
# -------- APPLY CLEANING --------
df["ARRIVAL_DELAY"] = df["ARRIVAL_DELAY"].fillna(0)
df["DEPARTURE_DELAY"] = df["DEPARTURE_DELAY"].fillna(0)
df["CANCELLED"] = df["CANCELLED"].fillna(0).astype(int)

In [21]:
# -------- CHECK AFTER --------
print("\nMissing Values AFTER:")
print(df[["ARRIVAL_DELAY", "DEPARTURE_DELAY", "CANCELLED"]].isnull().sum())

Missing Values AFTER:
ARRIVAL_DELAY      0
DEPARTURE_DELAY    0
CANCELLED          0
dtype: int64

In [22]:
# --------  Format Datetime Column BEFORE --------
print("FLIGHT_DATE exists before?", "FLIGHT_DATE" in df.columns)

# Create proper datetime column
df["FLIGHT_DATE"] = pd.to_datetime(df[["YEAR", "MONTH", "DAY"]])

# -------- AFTER --------
print("FLIGHT_DATE created.")
print(df["FLIGHT_DATE"].head())

FLIGHT_DATE exists before? False
FLIGHT_DATE created.
0   2015-01-01
1   2015-01-01
2   2015-01-01
3   2015-01-01
4   2015-01-01
Name: FLIGHT_DATE, dtype: datetime64[ns]

In [24]:
# --------   DERIVED FEATURES   --------
# Store original raw columns
df["DEPARTURE_TIME_BEFORE"] = df["DEPARTURE_TIME"]
df["MONTH_BEFORE"] = df["MONTH"]

# Create proper date column
df["FLIGHT_DATE"] = pd.to_datetime(df[["YEAR","MONTH","DAY"]])

# Derived features
df["MONTH_AFTER"] = df["FLIGHT_DATE"].dt.month
df["DAY_OF_WEEK"] = df["FLIGHT_DATE"].dt.dayofweek + 1
df["HOUR_AFTER"] = df["DEPARTURE_TIME"] // 100
df["ROUTE"] = df["ORIGIN_AIRPORT"].astype(str) + "-" + df["DESTINATION_AIRPORT"].astype(str)

comparison = df[[
    "DEPARTURE_TIME_BEFORE",
    "HOUR_AFTER",
    "MONTH_BEFORE",
    "MONTH_AFTER",
    "DAY_OF_WEEK",
    "ROUTE"
]].head()

print(comparison)

   DEPARTURE_TIME_BEFORE  HOUR_AFTER  MONTH_BEFORE  MONTH_AFTER  DAY_OF_WEEK  \
0                 2354.0        23.0             1            1            4
1                    2.0         0.0             1            1            4
2                   18.0         0.0             1            1            4
3                   15.0         0.0             1            1            4
4                   24.0         0.0             1            1            4

     ROUTE
0  ANC-SEA
1  LAX-PBI
2  SFO-CLT
3  LAX-MIA
4  SEA-ANC

In [25]:
# --------   REMOVE DUPLICATES   --------
rows_before = df.shape[0]

df.drop_duplicates(inplace=True)

rows_after = df.shape[0]

print("Rows Before:", rows_before)
print("Rows After:", rows_after)
print("Duplicates Removed:", rows_before - rows_after)

Rows Before: 5819079
Rows After: 5819079
Duplicates Removed: 0

In [27]:
# After all your cleaning steps
df.to_csv('/content/drive/MyDrive/cleaned_flights.csv', index=False)
print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [28]:
clean_df = pd.read_csv('/content/drive/MyDrive/cleaned_flights.csv')
clean_df.head()

/tmp/ipykernel_1929/1604880997.py:1: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  clean_df = pd.read_csv('/content/drive/MyDrive/cleaned_flights.csv')

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY,FLIGHT_DATE,DEPARTURE_TIME_BEFORE,MONTH_BEFORE,MONTH_AFTER,HOUR_AFTER,ROUTE
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,NaN,NaN,NaN,NaN,2015-01-01,2354.0,1,1,23.0,ANC-SEA
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,NaN,NaN,NaN,NaN,2015-01-01,2.0,1,1,0.0,LAX-PBI
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,NaN,NaN,NaN,NaN,2015-01-01,18.0,1,1,0.0,SFO-CLT
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,NaN,NaN,NaN,NaN,2015-01-01,15.0,1,1,0.0,LAX-MIA
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,NaN,NaN,NaN,NaN,2015-01-01,24.0,1,1,0.0,SEA-ANC